---
- name: Install Dependencies
  yum:
    name: httpd

- name: Start and enable httpd
  systemd:
    name: httpd.service
    state: started
    enabled: yes

- name: Add port into firewall
  firewalld:
    zone: public
    service: http
    state: enabled
    permanent: yes
    immediate: yes